[2022-01-21 20:24:12,640] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: extract_stat_players.extract_premier_ligue_players manual__2022-01-21T23:23:29.955157+00:00 [queued]>
[2022-01-21 20:24:12,646] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: extract_stat_players.extract_premier_ligue_players manual__2022-01-21T23:23:29.955157+00:00 [queued]>
[2022-01-21 20:24:12,646] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-21 20:24:12,646] {taskinstance.py:1239} INFO - Starting attempt 2 of 2
[2022-01-21 20:24:12,646] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-21 20:24:12,664] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extract_premier_ligue_players> on 2022-01-21 23:23:29.955157+00:00
[2022-01-21 20:24:12,667] {standard_task_runner.py:52} INFO - Started process 100717 to run task
[2022-01-21 20:24:12,674] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'extract_stat_players', 'extract_premier_ligue_players', 'manual__2022-01-21T23:23:29.955157+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/teste.py', '--cfg-path', '/tmp/tmpov4fyxqx', '--error-file', '/tmp/tmpa_rs4uvr']
[2022-01-21 20:24:12,675] {standard_task_runner.py:77} INFO - Job 45: Subtask extract_premier_ligue_players
[2022-01-21 20:24:12,766] {logging_mixin.py:109} INFO - Running <TaskInstance: extract_stat_players.extract_premier_ligue_players manual__2022-01-21T23:23:29.955157+00:00 [running]> on host dataeginner-VirtualBox
[2022-01-21 20:24:12,829] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=extract_stat_players
AIRFLOW_CTX_TASK_ID=extract_premier_ligue_players
AIRFLOW_CTX_EXECUTION_DATE=2022-01-21T23:23:29.955157+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-21T23:23:29.955157+00:00
[2022-01-21 20:24:12,838] {logging_mixin.py:109} INFO - Acess: https://fbref.com/en/comps/9/stats/Premier-League-Stats
[2022-01-21 20:24:14,751] {logging_mixin.py:109} INFO - datalake/raw/playes_premier_ligue/extract_date=2022-01-21
[2022-01-21 20:24:14,753] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 43, in extract_and_save_players
    save_json(
  File "/home/data-eginner/Documents/Soccer_Data/airflow//plugins/save_data.py", line 13, in save_json
    data.to_json(f"{path}/{table}_{datetime.strptime(date,'%Y/%m/%d')}.json",)
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-01-21' does not match format '%Y/%m/%d'
[2022-01-21 20:24:14,770] {taskinstance.py:1267} INFO - Marking task as FAILED. dag_id=extract_stat_players, task_id=extract_premier_ligue_players, execution_date=20220121T232329, start_date=20220121T232412, end_date=20220121T232414
[2022-01-21 20:24:14,819] {standard_task_runner.py:89} ERROR - Failed to execute job 45 for task extract_premier_ligue_players
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 43, in extract_and_save_players
    save_json(
  File "/home/data-eginner/Documents/Soccer_Data/airflow//plugins/save_data.py", line 13, in save_json
    data.to_json(f"{path}/{table}_{datetime.strptime(date,'%Y/%m/%d')}.json",)
  File "/usr/lib/python3.8/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-01-21' does not match format '%Y/%m/%d'
[2022-01-21 20:24:14,865] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-21 20:24:14,911] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
