[2022-01-28 21:27:18,680] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: extract_stat_players.extract_premier_ligue_players manual__2022-01-29T00:27:12.270760+00:00 [queued]>
[2022-01-28 21:27:18,695] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: extract_stat_players.extract_premier_ligue_players manual__2022-01-29T00:27:12.270760+00:00 [queued]>
[2022-01-28 21:27:18,707] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-28 21:27:18,707] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-28 21:27:18,707] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-28 21:27:18,762] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extract_premier_ligue_players> on 2022-01-29 00:27:12.270760+00:00
[2022-01-28 21:27:18,765] {standard_task_runner.py:52} INFO - Started process 23109 to run task
[2022-01-28 21:27:18,789] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'extract_stat_players', 'extract_premier_ligue_players', 'manual__2022-01-29T00:27:12.270760+00:00', '--job-id', '57', '--raw', '--subdir', '/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py', '--cfg-path', '/tmp/tmpl5jwv7w_', '--error-file', '/tmp/tmpqtrv__f6']
[2022-01-28 21:27:18,804] {standard_task_runner.py:77} INFO - Job 57: Subtask extract_premier_ligue_players
[2022-01-28 21:27:18,928] {logging_mixin.py:109} INFO - Running <TaskInstance: extract_stat_players.extract_premier_ligue_players manual__2022-01-29T00:27:12.270760+00:00 [running]> on host dataeginner-VirtualBox
[2022-01-28 21:27:19,085] {taskinstance.py:1424} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=extract_stat_players
AIRFLOW_CTX_TASK_ID=extract_premier_ligue_players
AIRFLOW_CTX_EXECUTION_DATE=2022-01-29T00:27:12.270760+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-29T00:27:12.270760+00:00
[2022-01-28 21:27:19,086] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: task_extrat_save_playes() missing 1 required positional argument: 'param'
[2022-01-28 21:27:19,110] {taskinstance.py:1267} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_stat_players, task_id=extract_premier_ligue_players, execution_date=20220129T002712, start_date=20220129T002718, end_date=20220129T002719
[2022-01-28 21:27:19,162] {standard_task_runner.py:89} ERROR - Failed to execute job 57 for task extract_premier_ligue_players
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 180, in _run_raw_task
    ti._run_raw_task(
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: task_extrat_save_playes() missing 1 required positional argument: 'param'
[2022-01-28 21:27:19,190] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-28 21:27:19,236] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
