[2022-01-28 20:49:24,739] {processor.py:163} INFO - Started process (PID=16311) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:49:24,753] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:49:24,754] {logging_mixin.py:109} INFO - [2022-01-28 20:49:24,754] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:49:24,830] {logging_mixin.py:109} INFO - [2022-01-28 20:49:24,800] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 6, in <module>
    from plugins.extract_stats_players import Extract_stats_players
ModuleNotFoundError: No module named 'plugins'
[2022-01-28 20:49:24,859] {processor.py:690} INFO - Deactivated 1 DAGs which are no longer present in /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:49:24,859] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:49:24,904] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 0.168 seconds
[2022-01-28 20:50:06,652] {processor.py:163} INFO - Started process (PID=16555) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:50:06,673] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:50:06,675] {logging_mixin.py:109} INFO - [2022-01-28 20:50:06,675] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:50:06,682] {logging_mixin.py:109} INFO - [2022-01-28 20:50:06,681] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 6, in <module>
    from plugins.extract_stats_players import Extract_stats_players
ModuleNotFoundError: No module named 'plugins'
[2022-01-28 20:50:06,693] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:50:06,709] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 0.062 seconds
[2022-01-28 20:50:44,427] {processor.py:163} INFO - Started process (PID=16727) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:50:44,487] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:50:44,487] {logging_mixin.py:109} INFO - [2022-01-28 20:50:44,487] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:50:44,535] {logging_mixin.py:109} INFO - [2022-01-28 20:50:44,492] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 6, in <module>
    from plugins.extract_stats_players import Extract_stats_players
ModuleNotFoundError: No module named 'plugins'
[2022-01-28 20:50:44,543] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:50:44,601] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 0.176 seconds
[2022-01-28 20:51:21,818] {processor.py:163} INFO - Started process (PID=16884) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:51:21,822] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:51:21,823] {logging_mixin.py:109} INFO - [2022-01-28 20:51:21,823] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:51:21,832] {logging_mixin.py:109} INFO - [2022-01-28 20:51:21,831] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 6, in <module>
    from plugins.extract_stats_players import Extract_stats_players
ModuleNotFoundError: No module named 'plugins'
[2022-01-28 20:51:21,841] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:51:21,856] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 0.043 seconds
[2022-01-28 20:51:57,037] {processor.py:163} INFO - Started process (PID=17211) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:51:57,066] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:51:57,066] {logging_mixin.py:109} INFO - [2022-01-28 20:51:57,066] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:51:57,078] {logging_mixin.py:109} INFO - [2022-01-28 20:51:57,078] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 6, in <module>
    from plugins.extract_stats_players import Extract_stats_players
ModuleNotFoundError: No module named 'plugins'
[2022-01-28 20:51:57,101] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:51:57,146] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 0.112 seconds
[2022-01-28 20:52:35,851] {processor.py:163} INFO - Started process (PID=17424) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:52:35,858] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:52:35,859] {logging_mixin.py:109} INFO - [2022-01-28 20:52:35,859] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:52:35,890] {logging_mixin.py:109} INFO - [2022-01-28 20:52:35,876] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 6, in <module>
    from plugins.extract_stats_players import Extract_stats_players
ModuleNotFoundError: No module named 'plugins'
[2022-01-28 20:52:35,916] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:52:35,974] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 0.139 seconds
[2022-01-28 20:53:19,050] {processor.py:163} INFO - Started process (PID=17609) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:53:19,069] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:53:19,071] {logging_mixin.py:109} INFO - [2022-01-28 20:53:19,071] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:53:20,986] {logging_mixin.py:109} INFO - [2022-01-28 20:53:20,986] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(),
TypeError: task_extrat_save_playes() missing 1 required positional argument: 'param'
[2022-01-28 20:53:21,003] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:53:21,154] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 2.123 seconds
[2022-01-28 20:54:01,177] {processor.py:163} INFO - Started process (PID=17760) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:54:01,180] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:54:01,181] {logging_mixin.py:109} INFO - [2022-01-28 20:54:01,181] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:54:02,680] {logging_mixin.py:109} INFO - [2022-01-28 20:54:02,679] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(),
TypeError: task_extrat_save_playes() missing 1 required positional argument: 'param'
[2022-01-28 20:54:02,691] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:54:02,738] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 1.563 seconds
[2022-01-28 20:54:44,576] {processor.py:163} INFO - Started process (PID=17903) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:54:44,583] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:54:44,583] {logging_mixin.py:109} INFO - [2022-01-28 20:54:44,583] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:54:46,621] {logging_mixin.py:109} INFO - [2022-01-28 20:54:46,620] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(),
TypeError: task_extrat_save_playes() missing 1 required positional argument: 'param'
[2022-01-28 20:54:46,660] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:54:46,698] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 2.155 seconds
[2022-01-28 20:55:27,560] {processor.py:163} INFO - Started process (PID=18054) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:55:27,566] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:55:27,568] {logging_mixin.py:109} INFO - [2022-01-28 20:55:27,567] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:55:28,854] {logging_mixin.py:109} INFO - [2022-01-28 20:55:28,850] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(teste),
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 48, in task_extrat_save_playes
    param.code_ligue,
AttributeError: 'dict' object has no attribute 'code_ligue'
[2022-01-28 20:55:28,886] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:55:28,928] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 1.371 seconds
[2022-01-28 20:56:20,897] {processor.py:163} INFO - Started process (PID=18224) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:56:20,922] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:56:20,923] {logging_mixin.py:109} INFO - [2022-01-28 20:56:20,923] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:56:22,712] {logging_mixin.py:109} INFO - [2022-01-28 20:56:22,711] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(teste),
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 48, in task_extrat_save_playes
    param.code_ligue,
AttributeError: 'dict' object has no attribute 'code_ligue'
[2022-01-28 20:56:22,746] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:56:22,802] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 1.907 seconds
[2022-01-28 20:57:05,430] {processor.py:163} INFO - Started process (PID=18374) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:57:05,441] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:57:05,443] {logging_mixin.py:109} INFO - [2022-01-28 20:57:05,443] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:57:06,346] {logging_mixin.py:109} INFO - [2022-01-28 20:57:06,345] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(teste),
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 48, in task_extrat_save_playes
    param.code_ligue,
AttributeError: 'dict' object has no attribute 'code_ligue'
[2022-01-28 20:57:06,357] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:57:06,389] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 0.975 seconds
[2022-01-28 20:57:42,396] {processor.py:163} INFO - Started process (PID=18505) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:57:42,410] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:57:42,411] {logging_mixin.py:109} INFO - [2022-01-28 20:57:42,411] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:57:43,655] {logging_mixin.py:109} INFO - [2022-01-28 20:57:43,654] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(teste),
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 48, in task_extrat_save_playes
    param.code_ligue,
AttributeError: 'dict' object has no attribute 'code_ligue'
[2022-01-28 20:57:43,669] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:57:43,697] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 1.304 seconds
[2022-01-28 20:58:30,151] {processor.py:163} INFO - Started process (PID=18671) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:58:30,171] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:58:30,171] {logging_mixin.py:109} INFO - [2022-01-28 20:58:30,171] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:58:32,393] {logging_mixin.py:109} INFO - [2022-01-28 20:58:32,372] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(teste),
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 48, in task_extrat_save_playes
    param.code_ligue,
AttributeError: 'dict' object has no attribute 'code_ligue'
[2022-01-28 20:58:32,404] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:58:32,461] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 2.313 seconds
[2022-01-28 20:59:33,963] {processor.py:163} INFO - Started process (PID=18843) to work on /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:59:33,993] {processor.py:642} INFO - Processing file /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py for tasks to queue
[2022-01-28 20:59:33,994] {logging_mixin.py:109} INFO - [2022-01-28 20:59:33,994] {dagbag.py:500} INFO - Filling up the DagBag from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:59:36,983] {logging_mixin.py:109} INFO - [2022-01-28 20:59:36,983] {dagbag.py:334} ERROR - Failed to import: /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
Traceback (most recent call last):
  File "/home/data-eginner/Documents/Soccer_Data/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 66, in <module>
    python_callable=task_extrat_save_playes(teste),
  File "/home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py", line 48, in task_extrat_save_playes
    param.code_ligue,
AttributeError: 'dict' object has no attribute 'code_ligue'
[2022-01-28 20:59:37,016] {processor.py:656} WARNING - No viable dags retrieved from /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py
[2022-01-28 20:59:37,079] {processor.py:171} INFO - Processing /home/data-eginner/Documents/Soccer_Data/airflow/dags/teste.py took 3.118 seconds
